export default {
  Axios: Symbol("Axios"),
  Casinos: Symbol("Casinos"),
  Curator: Symbol("Curator"),
  HandleErr: Symbol("HandleErr"),
  ControllerFactory: Symbol("ControllerFactory"),
  LibrarianFactory: Symbol("LibrarianFactory"),
  Logger: Symbol("Logger"),
  NarrationUrl: Symbol("NarrationUrl"),
  Repos: Symbol("Repos"),
  Router: Symbol("Router"),
  SniffHttp: Symbol("SniffHttp"),
  SniffWs: Symbol("SniffWs"),
  Stopwatch: Symbol("Stopwatch"),
  Storage: Symbol("Storage"),
  Tallier: Symbol("Tallier"),
  TokenCache: Symbol("TokenCache"),
  TokenGenerator: Symbol("TokenGenerator"),
  TokenName: Symbol("TokenName"),
  Wire: Symbol("Wire"),
};
