import { SniffedMessage } from "@tgiardina/sniff";

const events = [
  { pid: "PLAY_STAGE_INFO", stageNo: "4032459243" },
  {
    pid: "CO_OPTION_INFO",
    bblind: 5,
    sblind: 2,
    gameType: 2,
    gameType2: 1,
    hiLow: 0,
    maxSeat: 9,
    maxStakes: 0,
    minStakes: 0,
    real: 1,
  },
  {
    pid: "CO_TABLE_INFO",
    time: 7,
    currentSeat: 3,
    dealerSeat: 6,
    lockSeat: 0,
    tableState: 4,
    seatState: [0, 0, 80, 16, 0, 80, 0, 0, 0],
    account: [0, 0, 161, 150, 0, 486, 0, 0, 0],
    pbet: [0, 0, 0, 0, 0, 2, 0, 0, 0],
    curPot: [0, 0, 0, 0, 0, 0, 0, 0, 0],
    curRake: [0, 0, 0, 0, 0, 0, 0, 0, 0],
    potCount: 0,
    totalpot: 0,
  },
  { type: 3, data: 30, dwData: 30, pid: "SYS_INFO" },
  {
    pid: "PLAY_SEAT_INFO",
    type: 1,
    seat: 9,
    state: 16,
    account: 0,
    nickName: "560412658373500",
  },
  { type: 2, seat: 9, cash: 500, pid: "PLAY_ACCOUNT_CASH_RES" },
  { add: 0, seat: 9, pid: "PLAY_SEAT_RESERVATION" },
  { amountToPost: 5, pid: "CO_PRESELECT_BLINDS" },
  {
    pid: "CO_BLIND_INFO",
    seat: 3,
    account: 156,
    baseStakes: 0,
    btn: 4,
    bet: 5,
    dead: 0,
  },
  { tableState: 8, pid: "CO_TABLE_STATE" },
  { pid: "CO_CARDTABLE_INFO", seat3: [32896, 32896], seat6: [32896, 32896] },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  {
    type: 1,
    seat: 9,
    displayMax: 500,
    displayMin: 150,
    allowedMax: 0,
    allowedMin: 0,
    account: 983,
    defaultBuyin: 0,
    pid: "PLAY_BUYIN_INFO",
  },
  { seat: 9, chat: "_amIBlocked_", pid: "SYS_MSG_V2" },
  {
    pid: "PLAY_SEAT_INFO",
    type: 0,
    seat: 4,
    state: 16,
    account: 0,
    nickName: "",
  },
  { amountToPost: 0, pid: "CO_PRESELECT_BLINDS" },
  { pid: "CO_SELECT_INFO", seat: 6, btn: 512, bet: 3, raise: 13, account: 473 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 3, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "CO_SELECT_INFO",
    seat: 3,
    btn: 512,
    bet: 10,
    raise: 20,
    account: 136,
  },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 6, btn: 256, bet: 10, raise: 0, account: 463 },
  {
    pid: "CO_CHIPTABLE_INFO",
    seat: 0,
    potCount: 0,
    curPot: [50],
    curRake: [2],
  },
  { tableState: 16, pid: "CO_TABLE_STATE" },
  { bcard: [27, 44, 29], pid: "CO_BCARD3_INFO" },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 3, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 3, btn: 64, bet: 0, raise: 0, account: 136 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 6, btn: 64, bet: 0, raise: 0, account: 463 },
  {
    pid: "CO_CHIPTABLE_INFO",
    seat: 0,
    potCount: 0,
    curPot: [50],
    curRake: [2],
  },
  { tableState: 32, pid: "CO_TABLE_STATE" },
  { pos: 4, card: 4, pid: "CO_BCARD1_INFO" },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 3, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "PLAY_SEAT_INFO",
    type: 1,
    seat: 7,
    state: 16,
    account: 0,
    nickName: "",
  },
  { type: 2, seat: 7, cash: 300, pid: "PLAY_ACCOUNT_CASH_RES" },
  { add: 0, seat: 7, pid: "PLAY_SEAT_RESERVATION" },
  { amountToPost: 5, pid: "CO_PRESELECT_BLINDS" },
  { seat: 7, chat: "_amIBlocked_", pid: "SYS_MSG_V2" },
  { pid: "CO_SELECT_INFO", seat: 3, btn: 128, bet: 48, raise: 0, account: 88 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "CO_SELECT_INFO",
    seat: 6,
    btn: 4096,
    bet: 48,
    raise: 463,
    account: 0,
  },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 3, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 3, btn: 1024, bet: 0, raise: 0, account: 88 },
  {
    pid: "CO_CHIPTABLE_INFO",
    returnBet: 415,
    seat: 6,
    potCount: 0,
    curPot: [146],
    curRake: [7],
  },
  { tableState: 32768, pid: "CO_TABLE_STATE" },
  { type: 8, data: 0, dwData: 4, pid: "SYS_INFO" },
  { time: 5, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  { seat: 6, btn: 32768, pid: "CO_SHOW_INFO" },
  { tableState: 65536, pid: "CO_TABLE_STATE" },
  { pid: "CO_RESULT_INFO", account: [0, 0, 88, 0, 0, 554, 300, 0, 500] },
  {
    pid: "CO_POT_INFO",
    kicker: 0,
    kickerCard: [0, 0, 0, 0, 0, 0, 0, 0, 0],
    potNo: 0,
    returnHi: [0, 0, 0, 0, 0, 139, 0, 0, 0],
    returnLo: [0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  { pos: 5, card: 16, pid: "CO_RABBITCARD_INFO" },
  { pid: "PLAY_STAGE_END_REQ" },
  { pid: "PLAY_STAGE_INFO", stageNo: "4032459243" },
  { pid: "PLAY_CLEAR_INFO" },
  { seat: 6, pid: "CO_DEALER_SEAT" },
  { pid: "PLAY_STAGE_INFO", stageNo: "4032459793" },
  { tableState: 2, pid: "CO_TABLE_STATE" },
  { seat: 3, pid: "CO_DEALER_SEAT" },
  { seat: 3, pid: "CO_DEALER_SEAT" },
  { tableState: 4, pid: "CO_TABLE_STATE" },
  { time: 7, pid: "PLAY_TIME_INFO" },
  { seat: 3, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "CO_BLIND_INFO",
    seat: 3,
    account: 86,
    baseStakes: 0,
    btn: 2,
    bet: 2,
    dead: 0,
  },
  { time: 7, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "CO_BLIND_INFO",
    seat: 6,
    account: 549,
    baseStakes: 0,
    btn: 4,
    bet: 5,
    dead: 0,
  },
  { tableState: 8, pid: "CO_TABLE_STATE" },
  { pid: "CO_CARDTABLE_INFO", seat3: [32896, 32896], seat6: [32896, 32896] },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 3, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 3, btn: 512, bet: 3, raise: 13, account: 73 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 6, btn: 256, bet: 10, raise: 0, account: 539 },
  {
    pid: "CO_CHIPTABLE_INFO",
    seat: 0,
    potCount: 0,
    curPot: [30],
    curRake: [1],
  },
  { tableState: 16, pid: "CO_TABLE_STATE" },
  { bcard: [5, 7, 49], pid: "CO_BCARD3_INFO" },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 6, btn: 128, bet: 20, raise: 0, account: 519 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 3, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 3, btn: 1024, bet: 0, raise: 0, account: 73 },
  {
    pid: "CO_CHIPTABLE_INFO",
    returnBet: 20,
    seat: 6,
    potCount: 0,
    curPot: [30],
    curRake: [1],
  },
  { tableState: 32768, pid: "CO_TABLE_STATE" },
  { time: 5, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  { seat: 6, btn: 32768, pid: "CO_SHOW_INFO" },
  { tableState: 65536, pid: "CO_TABLE_STATE" },
  { pid: "CO_RESULT_INFO", account: [0, 0, 73, 0, 0, 568, 300, 0, 500] },
  {
    pid: "CO_POT_INFO",
    kicker: 0,
    kickerCard: [0, 0, 0, 0, 0, 0, 0, 0, 0],
    potNo: 0,
    returnHi: [0, 0, 0, 0, 0, 29, 0, 0, 0],
    returnLo: [0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  { pos: 4, card: 48, pid: "CO_RABBITCARD_INFO" },
  { pid: "PLAY_STAGE_END_REQ" },
  { pid: "PLAY_STAGE_INFO", stageNo: "4032459793" },
  { pid: "PLAY_CLEAR_INFO" },
  { seat: 3, pid: "CO_DEALER_SEAT" },
  { pid: "PLAY_STAGE_INFO", stageNo: "4032460173" },
  { tableState: 2, pid: "CO_TABLE_STATE" },
  { seat: 3, pid: "CO_DEALER_SEAT" },
  { seat: 3, pid: "CO_DEALER_SEAT" },
  { tableState: 4, pid: "CO_TABLE_STATE" },
  { time: 7, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "CO_BLIND_INFO",
    seat: 6,
    account: 566,
    baseStakes: 0,
    btn: 2,
    bet: 2,
    dead: 0,
  },
  { time: 7, pid: "PLAY_TIME_INFO" },
  { seat: 7, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "CO_BLIND_INFO",
    seat: 7,
    account: 295,
    baseStakes: 0,
    btn: 4,
    bet: 5,
    dead: 0,
  },
  { tableState: 8, pid: "CO_TABLE_STATE" },
  {
    pid: "CO_CARDTABLE_INFO",
    seat3: [32896, 32896],
    seat6: [32896, 32896],
    seat7: [32896, 32896],
  },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 3, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 3, btn: 1024, bet: 0, raise: 0, account: 73 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 6, btn: 1024, bet: 0, raise: 0, account: 566 },
  { pid: "CO_CHIPTABLE_INFO", seat: 7, potCount: 0, curPot: [7], curRake: [0] },
  { tableState: 32768, pid: "CO_TABLE_STATE" },
  { time: 5, pid: "PLAY_TIME_INFO" },
  { seat: 7, pid: "CO_CURRENT_PLAYER" },
  { seat: 7, btn: 32768, pid: "CO_SHOW_INFO" },
  { tableState: 65536, pid: "CO_TABLE_STATE" },
  { pid: "CO_RESULT_INFO", account: [0, 0, 73, 0, 0, 566, 302, 0, 500] },
  {
    pid: "CO_POT_INFO",
    kicker: 0,
    kickerCard: [0, 0, 0, 0, 0, 0, 0, 0, 0],
    potNo: 0,
    returnHi: [0, 0, 0, 0, 0, 0, 7, 0, 0],
    returnLo: [0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  { pid: "PLAY_STAGE_END_REQ" },
  { pid: "PLAY_STAGE_INFO", stageNo: "4032460173" },
  { pid: "PLAY_CLEAR_INFO" },
  { seat: 3, pid: "CO_DEALER_SEAT" },
  { pid: "PLAY_STAGE_INFO", stageNo: "4032460281" },
  { tableState: 2, pid: "CO_TABLE_STATE" },
  { seat: 6, pid: "CO_DEALER_SEAT" },
  { seat: 6, pid: "CO_DEALER_SEAT" },
  { play: 1, seat: 9, pid: "CO_SIT_PLAY" },
  { tableState: 4, pid: "CO_TABLE_STATE" },
  { time: 7, pid: "PLAY_TIME_INFO" },
  { seat: 7, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "CO_BLIND_INFO",
    seat: 7,
    account: 300,
    baseStakes: 0,
    btn: 2,
    bet: 2,
    dead: 0,
  },
  { time: 7, pid: "PLAY_TIME_INFO" },
  { seat: 9, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_BLIND_REQ", btns: 65540, bet: 5, dead: 0 },
  {
    pid: "CO_BLIND_INFO",
    seat: 9,
    account: 495,
    baseStakes: 0,
    btn: 4,
    bet: 5,
    dead: 0,
  },
  { tableState: 8, pid: "CO_TABLE_STATE" },
  {
    pid: "CO_CARDTABLE_INFO",
    seat3: [32896, 32896],
    seat6: [32896, 32896],
    seat7: [32896, 32896],
    seat9: [47, 16],
  },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 3, pid: "CO_CURRENT_PLAYER" },
  {
    btns: 130,
    selected: 0,
    bet: 0,
    call: 0,
    raise: 0,
    pid: "CO_SELECT_SPEED_BTN",
  },
  { pid: "CO_SELECT_INFO", seat: 3, btn: 1024, bet: 0, raise: 0, account: 73 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 6, btn: 512, bet: 5, raise: 15, account: 551 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 7, pid: "CO_CURRENT_PLAYER" },
  {
    btns: 9,
    selected: 0,
    bet: 0,
    call: 10,
    raise: 0,
    pid: "CO_SELECT_SPEED_BTN",
  },
  { pid: "CO_SELECT_INFO", seat: 7, btn: 1024, bet: 0, raise: 0, account: 300 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 9, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "CO_SELECT_REQ",
    btns: 40896256,
    bet: 10,
    raise: 25,
    maxRaise: 500,
    betPot: 47,
    halfPot: 26,
    timeBank: 30,
  },
  { account: 495, pid: "PLAY_ACCOUNT_INFO" },
  { play: 0, seat: 9, pid: "CO_SIT_PLAY" },
  { pid: "CO_SELECT_INFO", seat: 9, btn: 1024, bet: 0, raise: 0, account: 495 },
  {
    pid: "CO_CHIPTABLE_INFO",
    returnBet: 10,
    seat: 6,
    potCount: 0,
    curPot: [12],
    curRake: [0],
  },
  { tableState: 32768, pid: "CO_TABLE_STATE" },
  { time: 5, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  { seat: 6, btn: 32768, pid: "CO_SHOW_INFO" },
  { tableState: 65536, pid: "CO_TABLE_STATE" },
  { pid: "CO_RESULT_INFO", account: [0, 0, 73, 0, 0, 573, 300, 0, 495] },
  {
    pid: "CO_POT_INFO",
    kicker: 0,
    kickerCard: [0, 0, 0, 0, 0, 0, 0, 0, 0],
    potNo: 0,
    returnHi: [0, 0, 0, 0, 0, 12, 0, 0, 0],
    returnLo: [0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  { pid: "PLAY_STAGE_END_REQ" },
  { pid: "PLAY_STAGE_INFO", stageNo: "4032460281" },
  { pid: "CO_LAST_HAND_NUMBER", stageNo: "4032460281" },
  { pid: "PLAY_CLEAR_INFO" },
  { seat: 6, pid: "CO_DEALER_SEAT" },
  { pid: "PLAY_STAGE_INFO", stageNo: "4032460547" },
  { tableState: 2, pid: "CO_TABLE_STATE" },
  { seat: 7, pid: "CO_DEALER_SEAT" },
  { seat: 7, pid: "CO_DEALER_SEAT" },
  { play: 1, seat: 9, pid: "CO_SIT_PLAY" },
  { tableState: 4, pid: "CO_TABLE_STATE" },
  { time: 7, pid: "PLAY_TIME_INFO" },
  { seat: 9, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_BLIND_REQ", btns: 65538, bet: 2, dead: 0 },
  {
    pid: "CO_BLIND_INFO",
    seat: 9,
    account: 493,
    baseStakes: 0,
    btn: 2,
    bet: 2,
    dead: 0,
  },
  { time: 7, pid: "PLAY_TIME_INFO" },
  { seat: 3, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "CO_BLIND_INFO",
    seat: 3,
    account: 68,
    baseStakes: 0,
    btn: 4,
    bet: 5,
    dead: 0,
  },
  { tableState: 8, pid: "CO_TABLE_STATE" },
  {
    pid: "CO_CARDTABLE_INFO",
    seat3: [32896, 32896],
    seat6: [32896, 32896],
    seat7: [32896, 32896],
    seat9: [33, 44],
  },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  {
    btns: 9,
    selected: 0,
    bet: 0,
    call: 3,
    raise: 0,
    pid: "CO_SELECT_SPEED_BTN",
  },
  { pid: "CO_SELECT_INFO", seat: 6, btn: 512, bet: 5, raise: 15, account: 558 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 7, pid: "CO_CURRENT_PLAYER" },
  {
    btns: 9,
    selected: 0,
    bet: 0,
    call: 13,
    raise: 0,
    pid: "CO_SELECT_SPEED_BTN",
  },
  { pid: "CO_SELECT_INFO", seat: 7, btn: 256, bet: 15, raise: 0, account: 285 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 9, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "CO_SELECT_REQ",
    btns: 6293248,
    bet: 13,
    raise: 25,
    maxRaise: 495,
    betPot: 65,
    halfPot: 33,
    timeBank: 30,
  },
  { account: 493, pid: "PLAY_ACCOUNT_INFO" },
  { play: 0, seat: 9, pid: "CO_SIT_PLAY" },
  { pid: "CO_SELECT_INFO", seat: 9, btn: 1024, bet: 0, raise: 0, account: 493 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 3, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 3, btn: 1024, bet: 0, raise: 0, account: 68 },
  {
    pid: "CO_CHIPTABLE_INFO",
    seat: 0,
    potCount: 0,
    curPot: [37],
    curRake: [1],
  },
  { tableState: 16, pid: "CO_TABLE_STATE" },
  { bcard: [38, 23, 46], pid: "CO_BCARD3_INFO" },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 6, btn: 128, bet: 25, raise: 0, account: 533 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 7, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "PLAY_SEAT_INFO",
    type: 1,
    seat: 2,
    state: 16,
    account: 0,
    nickName: "",
  },
  { type: 2, seat: 2, cash: 500, pid: "PLAY_ACCOUNT_CASH_RES" },
  { add: 0, seat: 2, pid: "PLAY_SEAT_RESERVATION" },
  { amountToPost: 0, pid: "CO_PRESELECT_BLINDS" },
  { seat: 2, chat: "_amIBlocked_", pid: "SYS_MSG_V2" },
  { pid: "CO_SELECT_INFO", seat: 7, btn: 256, bet: 25, raise: 0, account: 260 },
  {
    pid: "CO_CHIPTABLE_INFO",
    seat: 0,
    potCount: 0,
    curPot: [87],
    curRake: [4],
  },
  { tableState: 32, pid: "CO_TABLE_STATE" },
  { pos: 4, card: 1, pid: "CO_BCARD1_INFO" },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "PLAY_SEAT_INFO",
    type: 1,
    seat: 8,
    state: 16,
    account: 0,
    nickName: "",
  },
  { type: 2, seat: 8, cash: 500, pid: "PLAY_ACCOUNT_CASH_RES" },
  { add: 0, seat: 8, pid: "PLAY_SEAT_RESERVATION" },
  { amountToPost: 0, pid: "CO_PRESELECT_BLINDS" },
  { seat: 8, chat: "_amIBlocked_", pid: "SYS_MSG_V2" },
  { pid: "CO_SELECT_INFO", seat: 6, btn: 64, bet: 0, raise: 0, account: 533 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 7, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 7, btn: 64, bet: 0, raise: 0, account: 260 },
  {
    pid: "CO_CHIPTABLE_INFO",
    seat: 0,
    potCount: 0,
    curPot: [87],
    curRake: [4],
  },
  { tableState: 64, pid: "CO_TABLE_STATE" },
  { pos: 5, card: 36, pid: "CO_BCARD1_INFO" },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 6, btn: 64, bet: 0, raise: 0, account: 533 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 7, pid: "CO_CURRENT_PLAYER" },
  { pid: "CO_SELECT_INFO", seat: 7, btn: 64, bet: 0, raise: 0, account: 260 },
  {
    pid: "CO_CHIPTABLE_INFO",
    seat: 0,
    potCount: 0,
    curPot: [87],
    curRake: [4],
  },
  { tableState: 32768, pid: "CO_TABLE_STATE" },
  { pid: "CO_PCARD_INFO", type: 0, seat: 6, card: [13, 20] },
  { seat: 6, btn: 8192, pid: "CO_SHOW_INFO" },
  { time: 5, pid: "PLAY_TIME_INFO" },
  { seat: 7, pid: "CO_CURRENT_PLAYER" },
  { seat: 7, btn: 16384, pid: "CO_SHOW_INFO" },
  { tableState: 65536, pid: "CO_TABLE_STATE" },
  {
    pid: "CO_RESULT_INFO",
    account: [0, 500, 68, 0, 0, 616, 260, 500, 493],
    handHi6: [6, 3, 4, 1, 0],
  },
  {
    pid: "CO_POT_INFO",
    kicker: 1,
    kickerCard: [0, 0, 0, 0, 0, 13, 0, 0, 0],
    potNo: 0,
    returnHi: [0, 0, 0, 0, 0, 83, 0, 0, 0],
    returnLo: [0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  { pid: "PLAY_STAGE_END_REQ" },
  { pid: "PLAY_STAGE_INFO", stageNo: "4032460547" },
  { pid: "CO_LAST_HAND_NUMBER", stageNo: "4032460547" },
  { pid: "PLAY_CLEAR_INFO" },
  { seat: 7, pid: "CO_DEALER_SEAT" },
  { pid: "PLAY_STAGE_INFO", stageNo: "4032461364" },
  { tableState: 2, pid: "CO_TABLE_STATE" },
  { seat: 9, pid: "CO_DEALER_SEAT" },
  { seat: 9, pid: "CO_DEALER_SEAT" },
  { play: 1, seat: 9, pid: "CO_SIT_PLAY" },
  { tableState: 4, pid: "CO_TABLE_STATE" },
  { time: 7, pid: "PLAY_TIME_INFO" },
  { seat: 3, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "CO_BLIND_INFO",
    seat: 3,
    account: 66,
    baseStakes: 0,
    btn: 2,
    bet: 2,
    dead: 0,
  },
  { time: 7, pid: "PLAY_TIME_INFO" },
  { seat: 6, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "CO_BLIND_INFO",
    seat: 6,
    account: 611,
    baseStakes: 0,
    btn: 4,
    bet: 5,
    dead: 0,
  },
  { time: 7, pid: "PLAY_TIME_INFO" },
  { seat: 8, pid: "CO_CURRENT_PLAYER" },
  {
    pid: "CO_BLIND_INFO",
    seat: 8,
    account: 495,
    baseStakes: 0,
    btn: 8,
    bet: 5,
    dead: 0,
  },
  { tableState: 8, pid: "CO_TABLE_STATE" },
  {
    pid: "CO_CARDTABLE_INFO",
    seat3: [32896, 32896],
    seat6: [32896, 32896],
    seat7: [32896, 32896],
    seat8: [32896, 32896],
    seat9: [22, 40],
  },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 7, pid: "CO_CURRENT_PLAYER" },
  {
    btns: 9,
    selected: 0,
    bet: 0,
    call: 5,
    raise: 0,
    pid: "CO_SELECT_SPEED_BTN",
  },
  { pid: "CO_SELECT_INFO", seat: 7, btn: 512, bet: 5, raise: 10, account: 250 },
  { time: 30, pid: "PLAY_TIME_INFO" },
  { seat: 8, pid: "CO_CURRENT_PLAYER" },
  {
    btns: 9,
    selected: 0,
    bet: 0,
    call: 10,
    raise: 0,
    pid: "CO_SELECT_SPEED_BTN",
  },
];

export default function wsSniffer(
  callback: (msg: SniffedMessage) => void
): void {
  events.forEach((event) => {
    callback({
      data: `0 | ${JSON.stringify({ ...event })}`,
      srcUrl:
        "https://www.bovada.lv/static/poker-game/?lobby=%2Fpoker-lobby%2Fhome%3Foverlay%3Djoin",
      targetUrl:
        "wss://pkscb.bovada.lv/poker-games/rgs?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.3.8-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json&X-atmo-protocol=true",
      tabId: 1,
    });
  });
}
